# This file was automatically generated by pywxrc.
# -*- coding: UTF-8 -*-

import wx
import wx.xrc as xrc

__res = None

def get_resources():
    """ This function provides access to the XML resources in this module."""
    global __res
    if __res == None:
        __init_resources()
    return __res




class xrcFRAME1(wx.Frame):
#!XRCED:begin-block:xrcFRAME1.PreCreate
    def PreCreate(self, pre):
        """ This function is called during the class's initialization.
        
        Override it for custom setup before the window is created usually to
        set additional window styles using SetWindowStyle() and SetExtraStyle().
        """
        pass
        
#!XRCED:end-block:xrcFRAME1.PreCreate

    def __init__(self, parent):
        # Two stage creation (see http://wiki.wxpython.org/index.cgi/TwoStageCreation)
        pre = wx.PreFrame()
        self.PreCreate(pre)
        get_resources().LoadOnFrame(pre, parent, "FRAME1")
        self.PostCreate(pre)

        # Define variables for the controls, bind event handlers
        self.panel1 = xrc.XRCCTRL(self, "panel1")
        self.quitBut = xrc.XRCCTRL(self, "quitBut")
        self.writeBut = xrc.XRCCTRL(self, "writeBut")
        self.fileBut = xrc.XRCCTRL(self, "fileBut")
        self.file_path = xrc.XRCCTRL(self, "file_path")
        self.plotspace = xrc.XRCCTRL(self, "plotspace")
        idx = self.GetMenuBar().FindMenu("File")
        if idx != wx.NOT_FOUND:
            self.fileMenu = self.GetMenuBar().GetMenu(idx)
        else:
            self.fileMenu = self.GetMenuBar().FindItemById(xrc.XRCID("fileMenu")).GetSubMenu()
        self.openMenu = self.GetMenuBar().FindItemById(xrc.XRCID("openMenu"))
        self.recMenu = self.GetMenuBar().FindItemById(xrc.XRCID("recMenu"))
        self.quitMenu = self.GetMenuBar().FindItemById(xrc.XRCID("quitMenu"))





# ------------------------ Resource data ----------------------

def __init_resources():
    global __res
    __res = xrc.EmptyXmlResource()

    __res.Load('wash_data.xrc')
